version: '3.4'
services:
  orborus:
      image: ghcr.io/gsoc2/gsoc2-orborus:nightly
      #hostname: gsoc2-orborus 
      environment:
        #GSOC2_WORKER_VERSION: nightly
        GSOC2_APP_SDK_VERSION: 0.8.97
        GSOC2_WORKER_VERSION: nightly
        BASE_URL: http://<BACKEND>:5001
        #BASE_URL: http://192.168.86.37:5001
        CLEANUP: 'true'
        DOCKER_API_VERSION: '1.40'
        ENVIRONMENT_NAME: Gsoc2
        HTTPS_PROXY: ''
        HTTP_PROXY: ''
        ORG_ID: Gsoc2
        GSOC2_BASE_IMAGE_NAME: gsoc2
        GSOC2_BASE_IMAGE_REGISTRY: ghcr.io
        GSOC2_BASE_IMAGE_TAG_SUFFIX: -0.8.80
        GSOC2_ORBORUS_EXECUTION_CONCURRENCY: '50'
        GSOC2_ORBORUS_EXECUTION_TIMEOUT: '800'
        GSOC2_PASS_APP_PROXY: 'FALSE'
        GSOC2_PASS_WORKER_PROXY: 'TRUE'
        GSOC2_SCALE_REPLICAS: 5
        GSOC2_SWARM_NETWORK_NAME: gsoc2_prod
        GSOC2_SWARM_CONFIG: "run"
      volumes:
       - /var/run/docker.sock:/var/run/docker.sock
      networks:
       - gsoc2_prod
       #- reverseproxy
      logging:
        driver: json-file

networks:
  gsoc2_prod:
    driver: overlay
    external: true
